train_data_dir: "/home/a116002/tensor/kl/data1/training.csv"
validation_data_dir: "/home/a116002/tensor/kl/data1/validation.csv"
test_data_dir: "/home/a116002/tensor/kl/data1/testing.csv"

batch_size: 128
learning_rate: 0.001
num_epochs: 50

data_loader: "ImageLoader"
color_mode: "L"  # L = bw or RGB
input_shape: [129, 500, 1]

model: "topcoder_crnn" # _finetune"

segment_length: 10  # number of seconds each spectogram represents
pixel_per_second: 50

label_names: ["EN", "HN", "AR", "BN", "CN"]
num_classes: 5

# label_names: ["EN", "DE", "FR", "ES", "CN", "RUS"]
# num_classes: 6




